FROM python:$PYTHON_VERSION-slim
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
# Python, don't write bytecode!
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 0

# -- Install Poetry:
RUN apt-get update && apt-get install -y build-essential git gettext-base curl

RUN python -m pip install -U "pip>20"
RUN python -m pip install "poetry==$POETRY_VERSION"
COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]