FROM python:$PYTHON_VERSION-slim
# Python, don't write bytecode!
ENV DEBIAN_FRONTEND=noninteractive \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=0

# -- Install Poetry:
RUN apt-get update && apt-get install -y build-essential git gettext-base curl

RUN python -m pip install -U "pip>=20.2"
RUN python -m pip install "poetry==$POETRY_VERSION"
COPY entrypoint.sh /
# ENTRYPOINT [ "/entrypoint.sh" ]