
name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-all-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [3.6, 3.7, 3.8]
        POETRY_VERSION: [1.0.10]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: create Dockerfile from template
      run: |
        envsubst < Dockerfile.template > Dockerfile
        if [[ "$PYTHON_VERSION" == 3.8 && "$POETRY_VERSION" == 1.0.10 ]]; then
            export TAG=${{matrix.PYTHON_VERSION}}-${{matrix.POETRY_VERSION}},latest
        else
            export TAG=${{matrix.PYTHON_VERSION}}-${{matrix.POETRY_VERSION}}
        fi
      env:
        PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
        POETRY_VERSION: ${{ matrix.POETRY_VERSION }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tolgaeren/poetry-in-a-container
        tags: $TAG
  